[package]
name = "conrete-edge-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"
bevy_gltf_components = "0.5.1"
bevy_registry_export = "0.3.1"
bevy_xpbd_3d = "0.4.2"
